[chore] Fix mdatagen generator issues with oracle cloud RDP (#46006)
The Oracle Cloud Resource Detection Processor (RDP) relies on the
`mdatagen` tool to generate code and config files from a source
`metadata.yaml` file. This is part of how this RDP initially came to
life.

At some point in the past few months, something changed with this
process, and `mdatagen` experiences errors when attempting to regenerate
the files for the Oracle Cloud Resource Detection Processor. This in
turn is blocking efforts to:

1. Add a new `realm` attribute to the RDP:
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/45890
2. Update the CODEOWNERS file to add myself as a code owner.

Rather than fixing the underlying issues as "ride along" issues
unrelated to the above 2 items, I'm breaking this out into a separate
chore PR for clarity.

With the previous `parent: resourcedetectionprocessor` declaration that
used to work in `metadata.yaml`, I was now getting this error when I
tried to run `mdatagen metadata.yaml`:

```
status must be empty for subcomponents
````

Just as @paulojmdias discovered in [a similar
PR](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/44424)

...it was now required to remove that parent declaration, and also to
change the format of the `type` from:

```
type: resourcedetectionprocessor/oraclecloud
```

...to:

```
type: oracleclouddetector
```

This matches many of the other detectors like Azure, DigitalOcean,
Dynatrace, etc. I've followed suit by making similar changes in this PR,
and now `mdatagen` cleanly generates files.

After making the above changes I was getting this error:

```
Error: ./generated_component_test.go:16:24: undefined: NewFactory
```

in a newly-generated test file:
`processor/resourcedetectionprocessor/internal/oraclecloud/generated_component_test.go`

I got some help from @paulojmdias on Slack who gave me this fix:

> Please copy this
[file](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/resourcedetectionprocessor/internal/azure/metadata.go)
to oraclecloud folder (and ofc rename the package name) there and run
make generate fmt lint test, and push the changes.

Once I did that, the compilation error went away.

I also copied the convention used by many other RDPs, including azure,
to include this in the `metadata.yaml`:

```
tests:
  skip_lifecycle: true
  skip_shutdown: true
```

...to avoid other unrelated test failures.

Also, somehow the descriptions for the attributes in `metadata.yaml` had
been replaced with non-descriptive descriptions at some point recently,
so I am restoring them.

<!--Describe what testing was performed and which tests were added.-->

* Ran `mdatagen` successfully.
* Ran `make generate fmt lint test`
* Built and deployed custom collector and verified functionality still
works.

<!--Please delete paragraphs that you did not use before submitting.-->